---
permalink: task-reconfigure-storage-systems-after-a-disaster-recovery-failback.html 
sidebar: sidebar 
keywords: fall, secondary, storage, system, snapmanager, hyper-v, complete, disaster, recovery, original, primary, storage, failback, reconfigure, reconfiguring 
summary: Tras producirse el fallo y conmutar al sistema de almacenamiento secundario, SnapManager para Hyper-V completa la recuperación ante desastres al conmutar por recuperación al sistema de almacenamiento principal original. 
---
= Volver a configurar los sistemas de almacenamiento después de una conmutación tras recuperación ante desastres
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Tras producirse el fallo y conmutar al sistema de almacenamiento secundario, SnapManager para Hyper-V completa la recuperación ante desastres al conmutar por recuperación al sistema de almacenamiento principal original. Tras volver a realizar, restaura la función de almacenamiento primario al sitio de almacenamiento primario original después de volver a habilitar o reemplazar sus sistemas de almacenamiento.

.Pasos
. Según la condición del sistema de almacenamiento primario, realice una de las siguientes acciones:
+
|===
| Si el sistema de almacenamiento primario es... | Realice lo siguiente... 


 a| 
Recuperables
 a| 
Mueva los datos del host secundario nuevamente al sistema de almacenamiento primario.



 a| 
Completamente destruido
 a| 
Aprovisione un nuevo sistema de almacenamiento.

|===
. Gestione la relación de SnapMirror:
+
.. Inicialice la relación de SnapMirror desde el sistema de almacenamiento secundario al sistema de almacenamiento principal para recuperar los datos.
.. Resincronice la relación de SnapMirror existente del sistema de almacenamiento secundario al sistema de almacenamiento primario.
.. Al utilizar SnapDrive en el sistema de almacenamiento secundario, inicie una actualización de SnapMirror para cada una de las LUN o recursos compartidos de SMB en el sistema de almacenamiento secundario.


. En función de la configuración, realice una de las siguientes acciones:
+
|===
| Si el sistema de almacenamiento primario es... | Realice lo siguiente... 


 a| 
Un host independiente (SAN)
 a| 
Conéctese a todos los puntos de montaje y LUN del sistema de almacenamiento principal del mismo tipo.



 a| 
Un host en clúster (SAN)
 a| 
Desde el nodo en el que el grupo de clústeres está en línea, conéctese a todos los puntos de montaje y LUN del clúster.



 a| 
Data ONTAP 8.1.x configurado con una única LUN que aloja máquinas virtuales en un volumen FlexVol (SAN) de origen
 a| 
Para que las actualizaciones de SnapMirror se lleven a cabo correctamente, debe crear un segundo LUN más pequeño (de 10 MB a 100 MB) en el volumen de FlexVol de origen antes de iniciar el trabajo de backup. Desde el nodo en el que el grupo de clústeres está en línea, conéctese a todos los puntos de montaje y LUN del clúster.



 a| 
Un host independiente o en clúster (NAS)
 a| 
Desmonte el volumen de protección de datos (DP), monte el volumen de protección de datos como regrabable, compruebe que el volumen tiene permisos RWX y, a continuación, cree recursos compartidos CIFS para los diferentes volúmenes.

|===
. Reconfigurar SnapInfo en función de su entorno:
+
|===
| Si la configuración es... | Realice lo siguiente... 


 a| 
SAN
 a| 
Restaurar la LUN de SnapInfo de su última copia Snapshot.



 a| 
NAS
 a| 
Monte el directorio SnapInfo.

|===
+
Para NAS, si se produce un error de denegación de acceso o si no puede desplazarse a la ubicación del recurso compartido de SMB expuesta, es posible que deba restablecer la ACL en el recurso compartido.

. Añada el host o clúster principal de SnapManager para Hyper-V MMC y configúrelo con la ruta de SnapInfo.
. Introduzca los siguientes cmdlets:
+
.. Recupere la lista de equipos virtuales presentes en los metadatos de copia de seguridad mediante el cmdlet Get-VMsFromBackup.
.. Obtenga las copias de backup de cada máquina virtual mediante el cmdlet Get-Backup para obtener las copias de backup de cada máquina virtual.


. Para restaurar, utilice `Restore-Backup` Con el GUID de la máquina virtual y la copia de backup con los siguientes parámetros:
+
|===
| Para restaurar desde... | Introduzca este comando... 


 a| 
Un host alternativo
 a| 
`Restore-Backup -Server` `Secondary_host_system_or_cluster_name -DisableVerifySnapshot -RestoreToAlternateHost`



 a| 
Una copia de backup enumerada
 a| 
`Restore-Backup -Server -VirtualMachinePath -SnapShotFilePath @VHD`

|===
+
Para `@VHD`, Un equipo virtual podría tener varios discos duros virtuales; debe introducir un par de ruta de origen y de destino especificado para cada disco duro virtual.

. Si el sistema host secundario es un clúster, complete los siguientes pasos:
+
.. Asegúrese de que las LUN en las que residen las máquinas virtuales estén en línea en el nodo de clúster propietario del grupo de clústeres.
.. Use los cmdlets de PowerShell para hacer que los equipos virtuales estén altamente disponibles.


+
Para NAS, una vez que se exponen las máquinas virtuales como recursos compartidos de SMB de un nodo de clúster, todos los hosts configurados para utilizar el clúster del sistema de almacenamiento pueden acceder a las máquinas virtuales.





== Ejemplos de conmutación por recuperación

El siguiente ejemplo muestra una configuración de dos clústeres en la que smhv-clúster-01 es el sitio principal y hv-19-cluster es el sitio secundario:

[listing]
----
PS C:\> Get-VMsFromBackup -Server smhv-cluster-01

winxp-x64c-135                593ABA72-B323-4AF7-9AC6-9514F64C0178
csv1-xp-3                     59B85C68-BAFA-4A49-8E85-A201045843F7
vm-w2k8r2sp1                  5A248757-872B-4FE7-8282-91C8E9D45CF9
um10_11_dr                    5AC1B2A8-6603-4F90-98F5-4F2F435AB0C2
winxp-x64c-30                 5B47D3CF-5D96-495D-9BAB-FB394392CF31
winxp-x64c-126                5B57EED1-B4F1-45A3-A649-24C6947CB79C
winxp-x64c-118                5B5D417B-70DC-427C-94BB-97FF81C5B92B
winxp-x64c-122                5BEE26B8-BE57-4879-A28E-9250A6A5EEFC
csv4-w2k3-19                  5D0613E5-B193-4293-8AAD-F8B94A5D851F

PS C:\> Get-Backup -Server smhv-cluster-01 -ResourceName
um10_11_dr

BackupName    : smhv-ccb-ds_04-10-2012_10.37.58
RetentionType : hourly
DatasetName   : smhv-ccb-ds
BackupId      : smhv-ccb-ds_04-10-2012_10.37.58
BackupTime    : 4/10/2012 10:37:58 AM
BackupType    : Application consistent
BackedupVMs   : {um10_11_dr}

PS C:\> Restore-Backup -Server smhv-cluster-01 -ResourceName
um10_11_dr -BackupName smhv-ccb-ds_04-10-2012_10.37.58
-DisableVerifySnapshot -RestoreToAlternateHost
----
El siguiente ejemplo muestra una operación DE restauración SAN en una ruta alternativa para la que N:\ es el destino y i:\ es la ruta de LUN de origen:

[listing]
----
PS C:\> Restore-Backup -Resourcename dr-san-ded1
-RestoreToAlternateHost -DisableVerifySnapshot -BackupName san_dr_09-11-2013_10.57.31 -Verbose
-VirtualMachinePath "N:\dr-san-ded1" -SnapshotFilePath "N:\dr-san-ded1" -VHDs @(@{"SourceFilePath" = "I:\dr-san-ded1\Virtual Hard Disks\dr-san-ded1.vhdx"; "DestinationFilePath" = "N:\dr-san-ded1\Virtual Hard Disks\dr-san-ded1"})
----
En el siguiente ejemplo, se muestra una operación de restauración NAS en una ruta alternativa donde \\172.17.162.174\ es la ruta del recurso compartido SMB de origen y \\172.17.175.82\ es la ruta del recurso compartido SMB de destino:

[listing]
----
PS C:\> Restore-Backup -Resourcename vm_claba87_cifs1
-RestoreToAlternateHost -DisableVerifySnapshot -BackupName ag-DR_09-09-2013_16.59.16 -Verbose
-VirtualMachinePath "\\172.17.175.82\vol_new_dest_share\ag-vm1" -SnapshotFilePath "\\172.17.175.82\vol_new_dest_share\ag-vm1" -VHDs @(@{"SourceFilePath" = "\\172.17.162.174\vol_test_src_share\ag-vm1\Virtual Hard Disks\ag-vm1.vhdx"; "DestinationFilePath" = "\\172.17.175.82\vol_new_dest_share\ag-vm1\Virtual Hard Disks\ag-vm1.vhdx"})
----
*Información relacionada*

https://library.netapp.com/ecm/ecm_download_file/ECMP1368826["Guía de recuperación y backup en línea de protección de datos de Data ONTAP 8.2 para 7-Mode"]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html["Referencia de SMB/CIFS"]
